
<!DOCTYPE html>
<html>
<head>
    <title>Nangsi Documention System</title>
</head>
<body>
    <p>Dear Dasho/Sir/Madam,</p>
    <p>{{ $body }}</p>
    <p><a href="{{$url}}">{{$filename}}</a></p>
    <p>Thanking you,</p>
    <br>
    <p>Yours Sincerely,</p><br>
    <p>({{ $name }})</p>
    <br/><strong>{{ $designation }}</strong></p>
    -----------------------<br/>
    <i>This email is generated by Nangsi Documentation System and please do not reply to this email. 
    However, you may forward to {{$email}}.</i>
    
</body>
</html>
